//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radyn.PaymentGateway.GhavaminGeteway {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sayanCard/merchant/definitions", ConfigurationName="GhavaminGeteway.merchant")]
    public interface merchant {
        
        // CODEGEN: Generating message contract since the operation getPaymentTicket is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketResponse1 getPaymentTicket(Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketRequest1 request);
        
        // CODEGEN: Generating message contract since the operation verify is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Radyn.PaymentGateway.GhavaminGeteway.verifyResponse1 verify(Radyn.PaymentGateway.GhavaminGeteway.verifyRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sayanCard/merchant/definitions")]
    public partial class getPaymentTicketRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchantIdField;
        
        private string wsp1Field;
        
        private string wsp2Field;
        
        private string amountField;
        
        private string paymentIdField;
        
        private string customerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string wsp1 {
            get {
                return this.wsp1Field;
            }
            set {
                this.wsp1Field = value;
                this.RaisePropertyChanged("wsp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string wsp2 {
            get {
                return this.wsp2Field;
            }
            set {
                this.wsp2Field = value;
                this.RaisePropertyChanged("wsp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string paymentId {
            get {
                return this.paymentIdField;
            }
            set {
                this.paymentIdField = value;
                this.RaisePropertyChanged("paymentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sayanCard/merchant/definitions")]
    public partial class errorOccur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sayanCard/merchant/definitions")]
    public partial class getPaymentTicketResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paymentTicketField;
        
        private errorOccur errorOccurField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string paymentTicket {
            get {
                return this.paymentTicketField;
            }
            set {
                this.paymentTicketField = value;
                this.RaisePropertyChanged("paymentTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public errorOccur errorOccur {
            get {
                return this.errorOccurField;
            }
            set {
                this.errorOccurField = value;
                this.RaisePropertyChanged("errorOccur");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentTicketRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sayanCard/merchant/definitions", Order=0)]
        public Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketRequest getPaymentTicketRequest;
        
        public getPaymentTicketRequest1() {
        }
        
        public getPaymentTicketRequest1(Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketRequest getPaymentTicketRequest) {
            this.getPaymentTicketRequest = getPaymentTicketRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentTicketResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sayanCard/merchant/definitions", Order=0)]
        public Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketResponse getPaymentTicketResponse;
        
        public getPaymentTicketResponse1() {
        }
        
        public getPaymentTicketResponse1(Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketResponse getPaymentTicketResponse) {
            this.getPaymentTicketResponse = getPaymentTicketResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sayanCard/merchant/definitions")]
    public partial class verifyRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchantIdField;
        
        private string wsp1Field;
        
        private string wsp2Field;
        
        private string paymentTicketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string wsp1 {
            get {
                return this.wsp1Field;
            }
            set {
                this.wsp1Field = value;
                this.RaisePropertyChanged("wsp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string wsp2 {
            get {
                return this.wsp2Field;
            }
            set {
                this.wsp2Field = value;
                this.RaisePropertyChanged("wsp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string paymentTicket {
            get {
                return this.paymentTicketField;
            }
            set {
                this.paymentTicketField = value;
                this.RaisePropertyChanged("paymentTicket");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sayanCard/merchant/definitions")]
    public partial class verifyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultCodeField;
        
        private string paymentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string paymentId {
            get {
                return this.paymentIdField;
            }
            set {
                this.paymentIdField = value;
                this.RaisePropertyChanged("paymentId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sayanCard/merchant/definitions", Order=0)]
        public Radyn.PaymentGateway.GhavaminGeteway.verifyRequest verifyRequest;
        
        public verifyRequest1() {
        }
        
        public verifyRequest1(Radyn.PaymentGateway.GhavaminGeteway.verifyRequest verifyRequest) {
            this.verifyRequest = verifyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sayanCard/merchant/definitions", Order=0)]
        public Radyn.PaymentGateway.GhavaminGeteway.verifyResponse verifyResponse;
        
        public verifyResponse1() {
        }
        
        public verifyResponse1(Radyn.PaymentGateway.GhavaminGeteway.verifyResponse verifyResponse) {
            this.verifyResponse = verifyResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface merchantChannel : Radyn.PaymentGateway.GhavaminGeteway.merchant, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class merchantClient : System.ServiceModel.ClientBase<Radyn.PaymentGateway.GhavaminGeteway.merchant>, Radyn.PaymentGateway.GhavaminGeteway.merchant {
        
        public merchantClient() {
        }
        
        public merchantClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public merchantClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public merchantClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public merchantClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketResponse1 Radyn.PaymentGateway.GhavaminGeteway.merchant.getPaymentTicket(Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketRequest1 request) {
            return base.Channel.getPaymentTicket(request);
        }
        
        public Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketResponse getPaymentTicket(Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketRequest getPaymentTicketRequest) {
            Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketRequest1 inValue = new Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketRequest1();
            inValue.getPaymentTicketRequest = getPaymentTicketRequest;
            Radyn.PaymentGateway.GhavaminGeteway.getPaymentTicketResponse1 retVal = ((Radyn.PaymentGateway.GhavaminGeteway.merchant)(this)).getPaymentTicket(inValue);
            return retVal.getPaymentTicketResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Radyn.PaymentGateway.GhavaminGeteway.verifyResponse1 Radyn.PaymentGateway.GhavaminGeteway.merchant.verify(Radyn.PaymentGateway.GhavaminGeteway.verifyRequest1 request) {
            return base.Channel.verify(request);
        }
        
        public Radyn.PaymentGateway.GhavaminGeteway.verifyResponse verify(Radyn.PaymentGateway.GhavaminGeteway.verifyRequest verifyRequest) {
            Radyn.PaymentGateway.GhavaminGeteway.verifyRequest1 inValue = new Radyn.PaymentGateway.GhavaminGeteway.verifyRequest1();
            inValue.verifyRequest = verifyRequest;
            Radyn.PaymentGateway.GhavaminGeteway.verifyResponse1 retVal = ((Radyn.PaymentGateway.GhavaminGeteway.merchant)(this)).verify(inValue);
            return retVal.verifyResponse;
        }
    }
}
