//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="RadynMessagesSoap", Namespace="http://tempuri.org/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataStructureBase))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SMS[]))]
public partial class RadynMessages : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback RadynSendGroupSmsOperationCompleted;
    
    private System.Threading.SendOrPostCallback RadynSendSmsOperationCompleted;
    
    private System.Threading.SendOrPostCallback RadynSearchSmSOperationCompleted;
    
    private System.Threading.SendOrPostCallback RadynResendSMSOperationCompleted;
    
    private System.Threading.SendOrPostCallback RadynGetAccountCreditOperationCompleted;
    
    /// <remarks/>
    public RadynMessages() {
        this.Url = "http://Radyn.ir/Services/RadynMessages.asmx";
    }
    
    /// <remarks/>
    public event RadynSendGroupSmsCompletedEventHandler RadynSendGroupSmsCompleted;
    
    /// <remarks/>
    public event RadynSendSmsCompletedEventHandler RadynSendSmsCompleted;
    
    /// <remarks/>
    public event RadynSearchSmSCompletedEventHandler RadynSearchSmSCompleted;
    
    /// <remarks/>
    public event RadynResendSMSCompletedEventHandler RadynResendSMSCompleted;
    
    /// <remarks/>
    public event RadynGetAccountCreditCompletedEventHandler RadynGetAccountCreditCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RadynSendGroupSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool RadynSendGroupSms(int accoutNumber, string username, string password, string[] to, string body) {
        object[] results = this.Invoke("RadynSendGroupSms", new object[] {
                    accoutNumber,
                    username,
                    password,
                    to,
                    body});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRadynSendGroupSms(int accoutNumber, string username, string password, string[] to, string body, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RadynSendGroupSms", new object[] {
                    accoutNumber,
                    username,
                    password,
                    to,
                    body}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndRadynSendGroupSms(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void RadynSendGroupSmsAsync(int accoutNumber, string username, string password, string[] to, string body) {
        this.RadynSendGroupSmsAsync(accoutNumber, username, password, to, body, null);
    }
    
    /// <remarks/>
    public void RadynSendGroupSmsAsync(int accoutNumber, string username, string password, string[] to, string body, object userState) {
        if ((this.RadynSendGroupSmsOperationCompleted == null)) {
            this.RadynSendGroupSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRadynSendGroupSmsOperationCompleted);
        }
        this.InvokeAsync("RadynSendGroupSms", new object[] {
                    accoutNumber,
                    username,
                    password,
                    to,
                    body}, this.RadynSendGroupSmsOperationCompleted, userState);
    }
    
    private void OnRadynSendGroupSmsOperationCompleted(object arg) {
        if ((this.RadynSendGroupSmsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RadynSendGroupSmsCompleted(this, new RadynSendGroupSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RadynSendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool RadynSendSms(int accoutNumber, string username, string password, string to, string body) {
        object[] results = this.Invoke("RadynSendSms", new object[] {
                    accoutNumber,
                    username,
                    password,
                    to,
                    body});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRadynSendSms(int accoutNumber, string username, string password, string to, string body, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RadynSendSms", new object[] {
                    accoutNumber,
                    username,
                    password,
                    to,
                    body}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndRadynSendSms(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void RadynSendSmsAsync(int accoutNumber, string username, string password, string to, string body) {
        this.RadynSendSmsAsync(accoutNumber, username, password, to, body, null);
    }
    
    /// <remarks/>
    public void RadynSendSmsAsync(int accoutNumber, string username, string password, string to, string body, object userState) {
        if ((this.RadynSendSmsOperationCompleted == null)) {
            this.RadynSendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRadynSendSmsOperationCompleted);
        }
        this.InvokeAsync("RadynSendSms", new object[] {
                    accoutNumber,
                    username,
                    password,
                    to,
                    body}, this.RadynSendSmsOperationCompleted, userState);
    }
    
    private void OnRadynSendSmsOperationCompleted(object arg) {
        if ((this.RadynSendSmsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RadynSendSmsCompleted(this, new RadynSendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RadynSearchSmS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public SMS[] RadynSearchSmS(int accoutNumber, string username, string password, string fromdate, string todate, string text, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<byte> status) {
        object[] results = this.Invoke("RadynSearchSmS", new object[] {
                    accoutNumber,
                    username,
                    password,
                    fromdate,
                    todate,
                    text,
                    status});
        return ((SMS[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRadynSearchSmS(int accoutNumber, string username, string password, string fromdate, string todate, string text, System.Nullable<byte> status, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RadynSearchSmS", new object[] {
                    accoutNumber,
                    username,
                    password,
                    fromdate,
                    todate,
                    text,
                    status}, callback, asyncState);
    }
    
    /// <remarks/>
    public SMS[] EndRadynSearchSmS(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SMS[])(results[0]));
    }
    
    /// <remarks/>
    public void RadynSearchSmSAsync(int accoutNumber, string username, string password, string fromdate, string todate, string text, System.Nullable<byte> status) {
        this.RadynSearchSmSAsync(accoutNumber, username, password, fromdate, todate, text, status, null);
    }
    
    /// <remarks/>
    public void RadynSearchSmSAsync(int accoutNumber, string username, string password, string fromdate, string todate, string text, System.Nullable<byte> status, object userState) {
        if ((this.RadynSearchSmSOperationCompleted == null)) {
            this.RadynSearchSmSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRadynSearchSmSOperationCompleted);
        }
        this.InvokeAsync("RadynSearchSmS", new object[] {
                    accoutNumber,
                    username,
                    password,
                    fromdate,
                    todate,
                    text,
                    status}, this.RadynSearchSmSOperationCompleted, userState);
    }
    
    private void OnRadynSearchSmSOperationCompleted(object arg) {
        if ((this.RadynSearchSmSCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RadynSearchSmSCompleted(this, new RadynSearchSmSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RadynResendSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool RadynResendSMS(System.Guid smsId) {
        object[] results = this.Invoke("RadynResendSMS", new object[] {
                    smsId});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRadynResendSMS(System.Guid smsId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RadynResendSMS", new object[] {
                    smsId}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndRadynResendSMS(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void RadynResendSMSAsync(System.Guid smsId) {
        this.RadynResendSMSAsync(smsId, null);
    }
    
    /// <remarks/>
    public void RadynResendSMSAsync(System.Guid smsId, object userState) {
        if ((this.RadynResendSMSOperationCompleted == null)) {
            this.RadynResendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRadynResendSMSOperationCompleted);
        }
        this.InvokeAsync("RadynResendSMS", new object[] {
                    smsId}, this.RadynResendSMSOperationCompleted, userState);
    }
    
    private void OnRadynResendSMSOperationCompleted(object arg) {
        if ((this.RadynResendSMSCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RadynResendSMSCompleted(this, new RadynResendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RadynGetAccountCredit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public decimal RadynGetAccountCredit(int accountId, string username, string password) {
        object[] results = this.Invoke("RadynGetAccountCredit", new object[] {
                    accountId,
                    username,
                    password});
        return ((decimal)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRadynGetAccountCredit(int accountId, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RadynGetAccountCredit", new object[] {
                    accountId,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public decimal EndRadynGetAccountCredit(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((decimal)(results[0]));
    }
    
    /// <remarks/>
    public void RadynGetAccountCreditAsync(int accountId, string username, string password) {
        this.RadynGetAccountCreditAsync(accountId, username, password, null);
    }
    
    /// <remarks/>
    public void RadynGetAccountCreditAsync(int accountId, string username, string password, object userState) {
        if ((this.RadynGetAccountCreditOperationCompleted == null)) {
            this.RadynGetAccountCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRadynGetAccountCreditOperationCompleted);
        }
        this.InvokeAsync("RadynGetAccountCredit", new object[] {
                    accountId,
                    username,
                    password}, this.RadynGetAccountCreditOperationCompleted, userState);
    }
    
    private void OnRadynGetAccountCreditOperationCompleted(object arg) {
        if ((this.RadynGetAccountCreditCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RadynGetAccountCreditCompleted(this, new RadynGetAccountCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class SMS : DataStructureBaseOfSMS {
    
    private byte deliveredField;
    
    private System.Guid idField;
    
    private string textField;
    
    private string keyField;
    
    private int accountIdField;
    
    private Account accountField;
    
    private decimal costField;
    
    private System.DateTime dateField;
    
    private string numberField;
    
    private int sMSCountField;
    
    private decimal sMSAmountField;
    
    /// <remarks/>
    public byte Delivered {
        get {
            return this.deliveredField;
        }
        set {
            this.deliveredField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public int AccountId {
        get {
            return this.accountIdField;
        }
        set {
            this.accountIdField = value;
        }
    }
    
    /// <remarks/>
    public Account Account {
        get {
            return this.accountField;
        }
        set {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    public decimal Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    public int SMSCount {
        get {
            return this.sMSCountField;
        }
        set {
            this.sMSCountField = value;
        }
    }
    
    /// <remarks/>
    public decimal SMSAmount {
        get {
            return this.sMSAmountField;
        }
        set {
            this.sMSAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Account : DataStructureBaseOfAccount {
    
    private int idField;
    
    private string titleField;
    
    private string usernameField;
    
    private string passwordField;
    
    private bool enabledField;
    
    private decimal creditField;
    
    private decimal sMSCostField;
    
    private decimal persianSMSCostField;
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    public decimal Credit {
        get {
            return this.creditField;
        }
        set {
            this.creditField = value;
        }
    }
    
    /// <remarks/>
    public decimal SMSCost {
        get {
            return this.sMSCostField;
        }
        set {
            this.sMSCostField = value;
        }
    }
    
    /// <remarks/>
    public decimal PersianSMSCost {
        get {
            return this.persianSMSCostField;
        }
        set {
            this.persianSMSCostField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Account))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public abstract partial class DataStructureBaseOfAccount : DataStructureBase {
    
    private ChangeTracker[] changesField;
    
    /// <remarks/>
    public ChangeTracker[] Changes {
        get {
            return this.changesField;
        }
        set {
            this.changesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ChangeTracker {
    
    private string objectNameField;
    
    private string fieldDescField;
    
    private string fieldNameField;
    
    private object oldValueField;
    
    private object newValueField;
    
    /// <remarks/>
    public string ObjectName {
        get {
            return this.objectNameField;
        }
        set {
            this.objectNameField = value;
        }
    }
    
    /// <remarks/>
    public string FieldDesc {
        get {
            return this.fieldDescField;
        }
        set {
            this.fieldDescField = value;
        }
    }
    
    /// <remarks/>
    public string FieldName {
        get {
            return this.fieldNameField;
        }
        set {
            this.fieldNameField = value;
        }
    }
    
    /// <remarks/>
    public object OldValue {
        get {
            return this.oldValueField;
        }
        set {
            this.oldValueField = value;
        }
    }
    
    /// <remarks/>
    public object NewValue {
        get {
            return this.newValueField;
        }
        set {
            this.newValueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataStructureBaseOfAccount))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Account))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DataStructureBaseOfSMS))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SMS))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public abstract partial class DataStructureBase {
    
    private ObjectState stateField;
    
    /// <remarks/>
    public ObjectState State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public enum ObjectState {
    
    /// <remarks/>
    None,
    
    /// <remarks/>
    New,
    
    /// <remarks/>
    Deleted,
    
    /// <remarks/>
    Dirty,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SMS))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public abstract partial class DataStructureBaseOfSMS : DataStructureBase {
    
    private ChangeTracker[] changesField;
    
    /// <remarks/>
    public ChangeTracker[] Changes {
        get {
            return this.changesField;
        }
        set {
            this.changesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void RadynSendGroupSmsCompletedEventHandler(object sender, RadynSendGroupSmsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RadynSendGroupSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RadynSendGroupSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void RadynSendSmsCompletedEventHandler(object sender, RadynSendSmsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RadynSendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RadynSendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void RadynSearchSmSCompletedEventHandler(object sender, RadynSearchSmSCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RadynSearchSmSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RadynSearchSmSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SMS[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SMS[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void RadynResendSMSCompletedEventHandler(object sender, RadynResendSMSCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RadynResendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RadynResendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void RadynGetAccountCreditCompletedEventHandler(object sender, RadynGetAccountCreditCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RadynGetAccountCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RadynGetAccountCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public decimal Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((decimal)(this.results[0]));
        }
    }
}
