//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormGenerator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormGenerator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FormGenerator", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowPrint.
        /// </summary>
        internal static string AllowPrint {
            get {
                return ResourceManager.GetString("AllowPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CssClass.
        /// </summary>
        internal static string CssClass {
            get {
                return ResourceManager.GetString("CssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Type.
        /// </summary>
        internal static string DateType {
            get {
                return ResourceManager.GetString("DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desgin Form.
        /// </summary>
        internal static string DesginForm {
            get {
                return ResourceManager.GetString("DesginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download File.
        /// </summary>
        internal static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessage.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertion.
        /// </summary>
        internal static string Expertion {
            get {
                return ResourceManager.GetString("Expertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} size is too permissive.
        /// </summary>
        internal static string Filesizeistoopermissive {
            get {
                return ResourceManager.GetString("Filesizeistoopermissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormData.
        /// </summary>
        internal static string FormData {
            get {
                return ResourceManager.GetString("FormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form design.
        /// </summary>
        internal static string Formdesign {
            get {
                return ResourceManager.GetString("Formdesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form List.
        /// </summary>
        internal static string FormList {
            get {
                return ResourceManager.GetString("FormList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GotoOrder.
        /// </summary>
        internal static string GotoOrder {
            get {
                return ResourceManager.GetString("GotoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsForce.
        /// </summary>
        internal static string IsForce {
            get {
                return ResourceManager.GetString("IsForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsImage?.
        /// </summary>
        internal static string IsImage {
            get {
                return ResourceManager.GetString("IsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size.
        /// </summary>
        internal static string MaxSize {
            get {
                return ResourceManager.GetString("MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Form.
        /// </summary>
        internal static string NewForm {
            get {
                return ResourceManager.GetString("NewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherPropertyName.
        /// </summary>
        internal static string OtherPropertyName {
            get {
                return ResourceManager.GetString("OtherPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseEnterOrderNumber.
        /// </summary>
        internal static string PleaseEnterOrderNumber {
            get {
                return ResourceManager.GetString("PleaseEnterOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter {0} value.
        /// </summary>
        internal static string PleaseEnterValue {
            get {
                return ResourceManager.GetString("PleaseEnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Columns.
        /// </summary>
        internal static string RepeatColumns {
            get {
                return ResourceManager.GetString("RepeatColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Direction.
        /// </summary>
        internal static string RepeatDirection {
            get {
                return ResourceManager.GetString("RepeatDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Time.
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextAlign.
        /// </summary>
        internal static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextMode.
        /// </summary>
        internal static string TextMode {
            get {
                return ResourceManager.GetString("TextMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Validation Typ already Added.
        /// </summary>
        internal static string ThisValidationTypalreadyAdded {
            get {
                return ResourceManager.GetString("ThisValidationTypalreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSelected.
        /// </summary>
        internal static string UnSelected {
            get {
                return ResourceManager.GetString("UnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Select Only One Item Selected.
        /// </summary>
        internal static string YouCanSelectOnlyOneItemSelected {
            get {
                return ResourceManager.GetString("YouCanSelectOnlyOneItemSelected", resourceCulture);
            }
        }
    }
}
