//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radyn.Payment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Payment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radyn.Payment.Resources.Payment", typeof(Payment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount code entere dis notcorrect.
        /// </summary>
        public static string Discountcodeenteredisnotcorrect {
            get {
                return ResourceManager.GetString("Discountcodeenteredisnotcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documnet.
        /// </summary>
        public static string Documnet {
            get {
                return ResourceManager.GetString("Documnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to an error in the operation of failed payment transactions.
        /// </summary>
        public static string Duetoanerrorintheoperationoffailedpaymenttransactions {
            get {
                return ResourceManager.GetString("Duetoanerrorintheoperationoffailedpaymenttransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter discount code has already been used.
        /// </summary>
        public static string Enterdiscountcodehasalreadybeenused {
            get {
                return ResourceManager.GetString("Enterdiscountcodehasalreadybeenused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Delete Discount.
        /// </summary>
        public static string ErrorInDeleteDiscount {
            get {
                return ResourceManager.GetString("ErrorInDeleteDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Delete Temp.
        /// </summary>
        public static string ErrorInDeleteTemp {
            get {
                return ResourceManager.GetString("ErrorInDeleteTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Discount.
        /// </summary>
        public static string ErrorInInsertDiscount {
            get {
                return ResourceManager.GetString("ErrorInInsertDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Discount Code.
        /// </summary>
        public static string ErrorInSaveDiscountCode {
            get {
                return ResourceManager.GetString("ErrorInSaveDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Transaction.
        /// </summary>
        public static string ErrorInSaveTransaction {
            get {
                return ResourceManager.GetString("ErrorInSaveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Transaction Discount.
        /// </summary>
        public static string ErrorInSaveTransactionDiscount {
            get {
                return ResourceManager.GetString("ErrorInSaveTransactionDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string GroupPayment {
            get {
                return ResourceManager.GetString("GroupPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information entered is not correct terminal.
        /// </summary>
        public static string Informationenteredisnotcorrectterminal {
            get {
                return ResourceManager.GetString("Informationenteredisnotcorrectterminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlinePay.
        /// </summary>
        public static string OnlinePay {
            get {
                return ResourceManager.GetString("OnlinePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Discount Attach File.
        /// </summary>
        public static string PleaseEnterDiscountAttachFile {
            get {
                return ResourceManager.GetString("PleaseEnterDiscountAttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Discount Code.
        /// </summary>
        public static string PleaseEnterDiscountCode {
            get {
                return ResourceManager.GetString("PleaseEnterDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Document Number.
        /// </summary>
        public static string PleaseEnterDocumentNumber {
            get {
                return ResourceManager.GetString("PleaseEnterDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter pay Amount.
        /// </summary>
        public static string PleaseEnterpayAmount {
            get {
                return ResourceManager.GetString("PleaseEnterpayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Pay Date.
        /// </summary>
        public static string PleaseEnterPayDate {
            get {
                return ResourceManager.GetString("PleaseEnterPayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Document ScanFile.
        /// </summary>
        public static string PleaseInsertDocumentScanFile {
            get {
                return ResourceManager.GetString("PleaseInsertDocumentScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal with the number not found.
        /// </summary>
        public static string Terminalwiththenumbernotfound {
            get {
                return ResourceManager.GetString("Terminalwiththenumbernotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in recording transactions..
        /// </summary>
        public static string Therewasanerrorinrecordingtransactions {
            get {
                return ResourceManager.GetString("Therewasanerrorinrecordingtransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been disabled.
        /// </summary>
        public static string Thisaccounthasbeendisabled {
            get {
                return ResourceManager.GetString("Thisaccounthasbeendisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Transaction Is End Please Start New Payment.
        /// </summary>
        public static string ThisTransactionIsEndPleaseStartNewPayment {
            get {
                return ResourceManager.GetString("ThisTransactionIsEndPleaseStartNewPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction NotFound.
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the capacity filled rebates.
        /// </summary>
        public static string Usingthecapacityfilledrebates {
            get {
                return ResourceManager.GetString("Usingthecapacityfilledrebates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Amount.
        /// </summary>
        public static string WithAmount {
            get {
                return ResourceManager.GetString("WithAmount", resourceCulture);
            }
        }
    }
}
