//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonComponent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonComponent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonComponent", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string BankEnabled {
            get {
                return ResourceManager.GetString("BankEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankLanguage.
        /// </summary>
        internal static string BankLanguage {
            get {
                return ResourceManager.GetString("BankLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankName.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string BankTitle {
            get {
                return ResourceManager.GetString("BankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country List.
        /// </summary>
        internal static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country New.
        /// </summary>
        internal static string CountryNew {
            get {
                return ResourceManager.GetString("CountryNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRange.
        /// </summary>
        internal static string EndRange {
            get {
                return ResourceManager.GetString("EndRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the security code is not valid.
        /// </summary>
        internal static string Enterthesecuritycodeisnotvalid {
            get {
                return ResourceManager.GetString("Enterthesecuritycodeisnotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageId.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageSize Not Allowed.
        /// </summary>
        internal static string Image_Size_Not_Allowed {
            get {
                return ResourceManager.GetString("Image_Size_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Is un valid.
        /// </summary>
        internal static string IpIsUnvalid {
            get {
                return ResourceManager.GetString("IpIsUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabled.
        /// </summary>
        internal static string LanguageDiabled {
            get {
                return ResourceManager.GetString("LanguageDiabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageDisplayName.
        /// </summary>
        internal static string LanguageDisplayName {
            get {
                return ResourceManager.GetString("LanguageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string LanguageEnabled {
            get {
                return ResourceManager.GetString("LanguageEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageLogo.
        /// </summary>
        internal static string LanguageLogoId {
            get {
                return ResourceManager.GetString("LanguageLogoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageName.
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageDiabled.
        /// </summary>
        internal static string LanguageStatus {
            get {
                return ResourceManager.GetString("LanguageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moth.
        /// </summary>
        internal static string Moth {
            get {
                return ResourceManager.GetString("Moth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parish.
        /// </summary>
        internal static string Parish {
            get {
                return ResourceManager.GetString("Parish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province List.
        /// </summary>
        internal static string ProvinceList {
            get {
                return ResourceManager.GetString("ProvinceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province New.
        /// </summary>
        internal static string ProvinceNew {
            get {
                return ResourceManager.GetString("ProvinceNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your message. &lt;br/&gt; Your message has been successfully sent to administrator.
        /// </summary>
        internal static string SentAdminMessage {
            get {
                return ResourceManager.GetString("SentAdminMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Logo Lanuage.
        /// </summary>
        internal static string ShowLogoLanuage {
            get {
                return ResourceManager.GetString("ShowLogoLanuage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartRange.
        /// </summary>
        internal static string StartRange {
            get {
                return ResourceManager.GetString("StartRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
