//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ContentManager", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        internal static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container List.
        /// </summary>
        internal static string ContainerList {
            get {
                return ResourceManager.GetString("ContainerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content List.
        /// </summary>
        internal static string ContentList {
            get {
                return ResourceManager.GetString("ContentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contentmanager.
        /// </summary>
        internal static string Contentmanager {
            get {
                return ResourceManager.GetString("Contentmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Name.
        /// </summary>
        internal static string ContextName {
            get {
                return ResourceManager.GetString("ContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Layout.
        /// </summary>
        internal static string DesigneLayout {
            get {
                return ResourceManager.GetString("DesigneLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Design page.
        /// </summary>
        internal static string EndDesign {
            get {
                return ResourceManager.GetString("EndDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Container ?.
        /// </summary>
        internal static string HasContainer {
            get {
                return ResourceManager.GetString("HasContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html List.
        /// </summary>
        internal static string HtmlList {
            get {
                return ResourceManager.GetString("HtmlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Url.
        /// </summary>
        internal static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISeSection?.
        /// </summary>
        internal static string ISeSection {
            get {
                return ResourceManager.GetString("ISeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISMenu?.
        /// </summary>
        internal static string ISMenu {
            get {
                return ResourceManager.GetString("ISMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWord.
        /// </summary>
        internal static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageId {
            get {
                return ResourceManager.GetString("LanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of menus.
        /// </summary>
        internal static string ListOfMenus {
            get {
                return ResourceManager.GetString("ListOfMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu List.
        /// </summary>
        internal static string MenuList {
            get {
                return ResourceManager.GetString("MenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleName.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Container.
        /// </summary>
        internal static string NewContainer {
            get {
                return ResourceManager.GetString("NewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Content.
        /// </summary>
        internal static string NewContent {
            get {
                return ResourceManager.GetString("NewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Html.
        /// </summary>
        internal static string NewHtml {
            get {
                return ResourceManager.GetString("NewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Menu.
        /// </summary>
        internal static string NewMenu {
            get {
                return ResourceManager.GetString("NewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exist To delete.
        /// </summary>
        internal static string Not_Exist_To_delete {
            get {
                return ResourceManager.GetString("Not_Exist_To_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exist To Edit.
        /// </summary>
        internal static string Not_Exist_To_Edit {
            get {
                return ResourceManager.GetString("Not_Exist_To_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageName.
        /// </summary>
        internal static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Partials {
            get {
                return ResourceManager.GetString("Partials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Menu.
        /// </summary>
        internal static string Please_select_Menu {
            get {
                return ResourceManager.GetString("Please_select_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Section.
        /// </summary>
        internal static string Please_select_Section {
            get {
                return ResourceManager.GetString("Please_select_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SectionParent.
        /// </summary>
        internal static string SectionParent {
            get {
                return ResourceManager.GetString("SectionParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Partials.
        /// </summary>
        internal static string StatePartials {
            get {
                return ResourceManager.GetString("StatePartials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item Not able to Delete Becase Have ChildNode.
        /// </summary>
        internal static string This_Item_Not_able_to_Delete_Becase_Have_ChildNode {
            get {
                return ResourceManager.GetString("This_Item_Not_able_to_Delete_Becase_Have_ChildNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item Not able to Delete Becase Have Content.
        /// </summary>
        internal static string This_Item_Not_able_to_Delete_Becase_Have_Content {
            get {
                return ResourceManager.GetString("This_Item_Not_able_to_Delete_Becase_Have_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Menu Not Have Content.
        /// </summary>
        internal static string This_Menu_Not_HaveContent {
            get {
                return ResourceManager.GetString("This_Menu_Not_HaveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Partial already Added to Element.
        /// </summary>
        internal static string This_Partial_already_Added_to_Element {
            get {
                return ResourceManager.GetString("This_Partial_already_Added_to_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Partial Not Added to Element.
        /// </summary>
        internal static string This_Partial_Not_Added_to_Element {
            get {
                return ResourceManager.GetString("This_Partial_Not_Added_to_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        internal static string UserScript {
            get {
                return ResourceManager.GetString("UserScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Content.
        /// </summary>
        internal static string ViewContent {
            get {
                return ResourceManager.GetString("ViewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitCount.
        /// </summary>
        internal static string VisitCount {
            get {
                return ResourceManager.GetString("VisitCount", resourceCulture);
            }
        }
    }
}
