//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class News {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal News() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.News", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to send to members of the newsletter?.
        /// </summary>
        internal static string Areyousureyouwanttosendnewsletter {
            get {
                return ResourceManager.GetString("Areyousureyouwanttosendnewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New News.
        /// </summary>
        internal static string NewNews {
            get {
                return ResourceManager.GetString("NewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsArchive.
        /// </summary>
        internal static string NewsArchive {
            get {
                return ResourceManager.GetString("NewsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string NewsCategoryEnabled {
            get {
                return ResourceManager.GetString("NewsCategoryEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        internal static string NewsCategoryParentCategoryId {
            get {
                return ResourceManager.GetString("NewsCategoryParentCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Title.
        /// </summary>
        internal static string NewsCategoryTitle {
            get {
                return ResourceManager.GetString("NewsCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string NewsContentBody {
            get {
                return ResourceManager.GetString("NewsContentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Content Language.
        /// </summary>
        internal static string NewsContentLanguageId {
            get {
                return ResourceManager.GetString("NewsContentLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        internal static string NewsContentLead {
            get {
                return ResourceManager.GetString("NewsContentLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Title.
        /// </summary>
        internal static string NewsContentOverTitle {
            get {
                return ResourceManager.GetString("NewsContentOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sutitr.
        /// </summary>
        internal static string NewsContentSutitr {
            get {
                return ResourceManager.GetString("NewsContentSutitr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title1.
        /// </summary>
        internal static string NewsContentTitle1 {
            get {
                return ResourceManager.GetString("NewsContentTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title2.
        /// </summary>
        internal static string NewsContentTitle2 {
            get {
                return ResourceManager.GetString("NewsContentTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeTitle.
        /// </summary>
        internal static string NewsContentTypeTitle {
            get {
                return ResourceManager.GetString("NewsContentTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitCount.
        /// </summary>
        internal static string NewsContentVisitCount {
            get {
                return ResourceManager.GetString("NewsContentVisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string NewsCreatorId {
            get {
                return ResourceManager.GetString("NewsCreatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string NewsEditorId {
            get {
                return ResourceManager.GetString("NewsEditorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string NewsEnabled {
            get {
                return ResourceManager.GetString("NewsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviewer.
        /// </summary>
        internal static string NewsInterviewerId {
            get {
                return ResourceManager.GetString("NewsInterviewerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News List.
        /// </summary>
        internal static string NewsList {
            get {
                return ResourceManager.GetString("NewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsNews {
            get {
                return ResourceManager.GetString("NewsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string NewsNewsCategoryId {
            get {
                return ResourceManager.GetString("NewsNewsCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Attachment.
        /// </summary>
        internal static string NewsPropertyHasAttachment {
            get {
                return ResourceManager.GetString("NewsPropertyHasAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Content Pic.
        /// </summary>
        internal static string NewsPropertyHasContentPic {
            get {
                return ResourceManager.GetString("NewsPropertyHasContentPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is General View ?.
        /// </summary>
        internal static string NewsPropertyIsGeneralView {
            get {
                return ResourceManager.GetString("NewsPropertyIsGeneralView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Image Report ?.
        /// </summary>
        internal static string NewsPropertyIsImageReport {
            get {
                return ResourceManager.GetString("NewsPropertyIsImageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Movie News ?.
        /// </summary>
        internal static string NewsPropertyIsMovieNews {
            get {
                return ResourceManager.GetString("NewsPropertyIsMovieNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is News Group Selection ?.
        /// </summary>
        internal static string NewsPropertyIsNewsGroupSelection {
            get {
                return ResourceManager.GetString("NewsPropertyIsNewsGroupSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Selection ?.
        /// </summary>
        internal static string NewsPropertyIsSelection {
            get {
                return ResourceManager.GetString("NewsPropertyIsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Sound News ?.
        /// </summary>
        internal static string NewsPropertyIsSoundNews {
            get {
                return ResourceManager.GetString("NewsPropertyIsSoundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Content Type ?.
        /// </summary>
        internal static string NewsPropertyNewsContentTypeId {
            get {
                return ResourceManager.GetString("NewsPropertyNewsContentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Group Order.
        /// </summary>
        internal static string NewsPropertyNewsGroupOrder {
            get {
                return ResourceManager.GetString("NewsPropertyNewsGroupOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string NewsPropertyOrder {
            get {
                return ResourceManager.GetString("NewsPropertyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string NewsPublishDate {
            get {
                return ResourceManager.GetString("NewsPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Time.
        /// </summary>
        internal static string NewsPublishTime {
            get {
                return ResourceManager.GetString("NewsPublishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Date.
        /// </summary>
        internal static string NewsSaveDate {
            get {
                return ResourceManager.GetString("NewsSaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Save Time.
        /// </summary>
        internal static string NewsSaveTime {
            get {
                return ResourceManager.GetString("NewsSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string NewsThumbnailId {
            get {
                return ResourceManager.GetString("NewsThumbnailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Title.
        /// </summary>
        internal static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pined.
        /// </summary>
        internal static string Pined {
            get {
                return ResourceManager.GetString("Pined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Type.
        /// </summary>
        internal static string PublishTypeTitle {
            get {
                return ResourceManager.GetString("PublishTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Category Not have News.
        /// </summary>
        internal static string This_Category_Not_have_News {
            get {
                return ResourceManager.GetString("This_Category_Not_have_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
