//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PhoneBook {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhoneBook() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PhoneBook", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        internal static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defult phone Number.
        /// </summary>
        internal static string DefultphoneNumber {
            get {
                return ResourceManager.GetString("DefultphoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deparment.
        /// </summary>
        internal static string Deparment {
            get {
                return ResourceManager.GetString("Deparment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepartmentName.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Report.
        /// </summary>
        internal static string ExcelReport {
            get {
                return ResourceManager.GetString("ExcelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Size Not Alowed.
        /// </summary>
        internal static string Image_Size_Not_Alowed {
            get {
                return ResourceManager.GetString("Image_Size_Not_Alowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTitle.
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Config.
        /// </summary>
        internal static string NotConfig {
            get {
                return ResourceManager.GetString("NotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfficeName.
        /// </summary>
        internal static string OfficeName {
            get {
                return ResourceManager.GetString("OfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersoneliCode.
        /// </summary>
        internal static string PersoneliCode {
            get {
                return ResourceManager.GetString("PersoneliCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Type.
        /// </summary>
        internal static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Job Title.
        /// </summary>
        internal static string PleaseEnterJobTitle {
            get {
                return ResourceManager.GetString("PleaseEnterJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Minimom Of Address.
        /// </summary>
        internal static string PleaseEnterMinimomOfAddress {
            get {
                return ResourceManager.GetString("PleaseEnterMinimomOfAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Departmen.
        /// </summary>
        internal static string Please_Enter_Departmen {
            get {
                return ResourceManager.GetString("Please_Enter_Departmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        internal static string Please_Enter_Email {
            get {
                return ResourceManager.GetString("Please_Enter_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter FName.
        /// </summary>
        internal static string Please_Enter_FName {
            get {
                return ResourceManager.GetString("Please_Enter_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Lname.
        /// </summary>
        internal static string Please_Enter_Lname {
            get {
                return ResourceManager.GetString("Please_Enter_Lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Office.
        /// </summary>
        internal static string Please_Enter_Office {
            get {
                return ResourceManager.GetString("Please_Enter_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Personeli Code.
        /// </summary>
        internal static string Please_Enter_PersoneliCode {
            get {
                return ResourceManager.GetString("Please_Enter_PersoneliCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter TelPhone.
        /// </summary>
        internal static string Please_Enter_Tel {
            get {
                return ResourceManager.GetString("Please_Enter_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string Please_wait {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchKeyword.
        /// </summary>
        internal static string SearchKeyword {
            get {
                return ResourceManager.GetString("SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelNumber.
        /// </summary>
        internal static string TelNumber {
            get {
                return ResourceManager.GetString("TelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
