//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radyn.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radyn.Common.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aban.
        /// </summary>
        public static string Aban {
            get {
                return ResourceManager.GetString("Aban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        public static string Autumn {
            get {
                return ResourceManager.GetString("Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azar.
        /// </summary>
        public static string Azar {
            get {
                return ResourceManager.GetString("Azar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahman.
        /// </summary>
        public static string Bahman {
            get {
                return ResourceManager.GetString("Bahman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string Dolar {
            get {
                return ResourceManager.GetString("Dolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfand.
        /// </summary>
        public static string Esfand {
            get {
                return ResourceManager.GetString("Esfand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farvardin.
        /// </summary>
        public static string Farvardin {
            get {
                return ResourceManager.GetString("Farvardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstWeek.
        /// </summary>
        public static string FirstWeek {
            get {
                return ResourceManager.GetString("FirstWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiveWeek.
        /// </summary>
        public static string FiveWeek {
            get {
                return ResourceManager.GetString("FiveWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FourWeek.
        /// </summary>
        public static string FourWeek {
            get {
                return ResourceManager.GetString("FourWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khordad.
        /// </summary>
        public static string Khordad {
            get {
                return ResourceManager.GetString("Khordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr.
        /// </summary>
        public static string Mehr {
            get {
                return ResourceManager.GetString("Mehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordad.
        /// </summary>
        public static string Mordad {
            get {
                return ResourceManager.GetString("Mordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordibehesht.
        /// </summary>
        public static string Ordibehesht {
            get {
                return ResourceManager.GetString("Ordibehesht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondWeek.
        /// </summary>
        public static string SecondWeek {
            get {
                return ResourceManager.GetString("SecondWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharhrivar.
        /// </summary>
        public static string Sharhrivar {
            get {
                return ResourceManager.GetString("Sharhrivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SunDay.
        /// </summary>
        public static string SunDay {
            get {
                return ResourceManager.GetString("SunDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thersday.
        /// </summary>
        public static string Thersday {
            get {
                return ResourceManager.GetString("Thersday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThirdWeek.
        /// </summary>
        public static string ThirdWeek {
            get {
                return ResourceManager.GetString("ThirdWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thurday.
        /// </summary>
        public static string Thurday {
            get {
                return ResourceManager.GetString("Thurday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mordad.
        /// </summary>
        public static string Tir {
            get {
                return ResourceManager.GetString("Tir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wensday.
        /// </summary>
        public static string Wensday {
            get {
                return ResourceManager.GetString("Wensday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
    }
}
