//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advertisement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advertisement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Advertisement", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Count.
        /// </summary>
        internal static string AdsShowCount {
            get {
                return ResourceManager.GetString("AdsShowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClickCount.
        /// </summary>
        internal static string AdvertisementClickCount {
            get {
                return ResourceManager.GetString("AdvertisementClickCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement Count.
        /// </summary>
        internal static string AdvertisementCount {
            get {
                return ResourceManager.GetString("AdvertisementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string AdvertisementEnable {
            get {
                return ResourceManager.GetString("AdvertisementEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement File.
        /// </summary>
        internal static string AdvertisementFileId {
            get {
                return ResourceManager.GetString("AdvertisementFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View FromDate.
        /// </summary>
        internal static string AdvertisementFromDate {
            get {
                return ResourceManager.GetString("AdvertisementFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string AdvertisementHeight {
            get {
                return ResourceManager.GetString("AdvertisementHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigateUrl.
        /// </summary>
        internal static string AdvertisementNavigateUrl {
            get {
                return ResourceManager.GetString("AdvertisementNavigateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string AdvertisementPositionId {
            get {
                return ResourceManager.GetString("AdvertisementPositionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        internal static string Advertisements {
            get {
                return ResourceManager.GetString("Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string AdvertisementText {
            get {
                return ResourceManager.GetString("AdvertisementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View ToDate.
        /// </summary>
        internal static string AdvertisementToDate {
            get {
                return ResourceManager.GetString("AdvertisementToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement Type.
        /// </summary>
        internal static string AdvertisementTypeId {
            get {
                return ResourceManager.GetString("AdvertisementTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitCount.
        /// </summary>
        internal static string AdvertisementVisitCount {
            get {
                return ResourceManager.GetString("AdvertisementVisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Advertisementwidth {
            get {
                return ResourceManager.GetString("Advertisementwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Count.
        /// </summary>
        internal static string ClickCount {
            get {
                return ResourceManager.GetString("ClickCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement System.
        /// </summary>
        internal static string ComponentTitle {
            get {
                return ResourceManager.GetString("ComponentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Count.
        /// </summary>
        internal static string DayCount {
            get {
                return ResourceManager.GetString("DayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Word.
        /// </summary>
        internal static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Click.
        /// </summary>
        internal static string PerClick {
            get {
                return ResourceManager.GetString("PerClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Day.
        /// </summary>
        internal static string PerDay {
            get {
                return ResourceManager.GetString("PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Visit.
        /// </summary>
        internal static string PerVisit {
            get {
                return ResourceManager.GetString("PerVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section  KeyWord.
        /// </summary>
        internal static string SectionKeyWord {
            get {
                return ResourceManager.GetString("SectionKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SectionPosition.
        /// </summary>
        internal static string SectionPosition {
            get {
                return ResourceManager.GetString("SectionPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string SectionPositionKeyWord {
            get {
                return ResourceManager.GetString("SectionPositionKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Count.
        /// </summary>
        internal static string ShowCount {
            get {
                return ResourceManager.GetString("ShowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Time.
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff.
        /// </summary>
        internal static string Tariff {
            get {
                return ResourceManager.GetString("Tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Class.
        /// </summary>
        internal static string TariffClass {
            get {
                return ResourceManager.GetString("TariffClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        internal static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Count.
        /// </summary>
        internal static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Count.
        /// </summary>
        internal static string VisitCount {
            get {
                return ResourceManager.GetString("VisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
