//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Statistics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Statistics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Statistics", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Moth View Count.
        /// </summary>
        internal static string CurrentMothViewCount {
            get {
                return ResourceManager.GetString("CurrentMothViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Moth Viewer Count.
        /// </summary>
        internal static string CurrentMothViewerCount {
            get {
                return ResourceManager.GetString("CurrentMothViewerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days View Count.
        /// </summary>
        internal static string Last7DaysViewCount {
            get {
                return ResourceManager.GetString("Last7DaysViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days Viewer Count.
        /// </summary>
        internal static string Last7DaysViewerCount {
            get {
                return ResourceManager.GetString("Last7DaysViewerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month View Count.
        /// </summary>
        internal static string LastMothViewCount {
            get {
                return ResourceManager.GetString("LastMothViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastMoth Viewer Count.
        /// </summary>
        internal static string LastMothViewerCount {
            get {
                return ResourceManager.GetString("LastMothViewerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastWeek Viewer Count.
        /// </summary>
        internal static string LastWeekViewerCount {
            get {
                return ResourceManager.GetString("LastWeekViewerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moth Viewer Count.
        /// </summary>
        internal static string MothViewerCount {
            get {
                return ResourceManager.GetString("MothViewerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        internal static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Title .
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today View .
        /// </summary>
        internal static string TodayViewCount {
            get {
                return ResourceManager.GetString("TodayViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Viewer Count.
        /// </summary>
        internal static string TodayViewerCount {
            get {
                return ResourceManager.GetString("TodayViewerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total View.
        /// </summary>
        internal static string TotalView {
            get {
                return ResourceManager.GetString("TotalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YesterDay view .
        /// </summary>
        internal static string YesterDayviewCount {
            get {
                return ResourceManager.GetString("YesterDayviewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YesterDay Vewer Count.
        /// </summary>
        internal static string YesterDayviewerCount {
            get {
                return ResourceManager.GetString("YesterDayviewerCount", resourceCulture);
            }
        }
    }
}
